# Generated by Django 5.2 on 2025-04-20 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('funding_rate', models.FloatField()),
                ('funding_time', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['symbol', 'timestamp'], name='data_collec_symbol_8a0a36_idx')],
            },
        ),
        migrations.CreateModel(
            name='Liquidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('side', models.CharField(max_length=10)),
                ('quantity', models.FloatField()),
                ('price', models.FloatField()),
            ],
            options={
                'indexes': [models.Index(fields=['symbol', 'timestamp'], name='data_collec_symbol_87c032_idx')],
            },
        ),
        migrations.CreateModel(
            name='OpenInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('open_interest', models.FloatField()),
            ],
            options={
                'indexes': [models.Index(fields=['symbol', 'timestamp'], name='data_collec_symbol_c9ea46_idx')],
            },
        ),
        migrations.CreateModel(
            name='TradeVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('volume', models.FloatField()),
                ('buy_volume', models.FloatField()),
                ('sell_volume', models.FloatField()),
            ],
            options={
                'indexes': [models.Index(fields=['symbol', 'timestamp'], name='data_collec_symbol_5e873c_idx')],
            },
        ),
    ]
