# Generated by Django 5.2 on 2025-04-20 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0002_fundingrate_liquidation_openinterest_tradevolume'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fundingrate',
            table='data_collection_fundingrate',
        ),
        migrations.AlterModelTable(
            name='liquidation',
            table='data_collection_liquidation',
        ),
        migrations.AlterModelTable(
            name='openinterest',
            table='data_collection_openinterest',
        ),
        migrations.AlterModelTable(
            name='orderbook',
            table='data_collection_orderbook',
        ),
        migrations.AlterModelTable(
            name='tradevolume',
            table='data_collection_tradevolume',
        ),
    ]
