# Generated by Django 5.2 on 2025-04-20 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('bids', models.JSONField()),
                ('asks', models.JSONField()),
            ],
            options={
                'indexes': [models.Index(fields=['symbol', 'timestamp'], name='data_collec_symbol_7e6772_idx')],
            },
        ),
    ]
